Crozatier = {}; Crozatier.stuff = [
  {
    "brand": "VIVA",
    "name": "Stove Hood",
    "model": "VVA62U150",
    "slug": "stove-hood",
    "delta": "€ 43.60",
    "details": "Stainless Steel, 3 speed with 40watt lightbulb",
    "asking_cost": "€ 40",
    "percent_discount": "52.1531100478469%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 83.60",
    "docs": ""
  },
  {
    "brand": "VIVA",
    "name": "Oven",
    "model": "VVH32C3320",
    "slug": "oven",
    "delta": "€ 176.16",
    "details": "52L - White - 6 cooking modes with clock",
    "asking_cost": "€ 175",
    "percent_discount": "50.1651668754984%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 351.16",
    "docs": ""
  },
  {
    "brand": "Glem",
    "name": "Glass Cooktop",
    "model": "XTDH5C",
    "slug": "glass-cooktop",
    "delta": "€ 157.61",
    "details": "2 surfaces with front controls",
    "asking_cost": "€ 125",
    "percent_discount": "55.7694349103004%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 282.61",
    "docs": "yes"
  },
  {
    "brand": "VIVA",
    "name": "Freezer/Fridge",
    "model": "VVC36V00F",
    "slug": "fridge",
    "delta": "€ 218.06",
    "details": "Fridge 225L, Freezer 87L with 3 drawers. Fridge on top",
    "asking_cost": "€ 200",
    "percent_discount": "52.159977036789%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 418.06",
    "docs": "yes"
  },
  {
    "brand": "Siemens",
    "name": "Dishwasher",
    "model": "SF24E233EU",
    "slug": "dishwasher",
    "delta": "€ 226.42",
    "details": "Dishwasher (9 couverts, 4 programs)",
    "asking_cost": "€ 200",
    "percent_discount": "53.0978847146006%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 426.42",
    "docs": "yes"
  },
  {
    "brand": "Siemens",
    "name": "Washer/Dryer",
    "model": "WD12D560FF",
    "slug": "washer-dryer",
    "delta": "€ 347.26",
    "details": "Combo washer-dryer. 5kg capacity. 8 buttons / 15 programs.",
    "asking_cost": "€ 330",
    "percent_discount": "51.2742521335971%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 677.26",
    "docs": ""
  },
  {
    "brand": "Dyson",
    "name": "Vacuum Cleaner",
    "model": "DC19 Origin",
    "slug": "vacuum",
    "delta": "€ 130.59",
    "details": "Bagless",
    "asking_cost": "€ 100",
    "percent_discount": "56.6329849516458%",
    "purchase_date": "1/29/2009",
    "original_cost": "€ 230.59",
    "docs": "yes"
  },
  {
    "brand": "Cuisinart",
    "name": "Sandwich Press / Electric Grill",
    "model": "CLASS PRO GR4E",
    "slug": "sandwich-press",
    "delta": "€ 119.17",
    "details": "2 sets of surfaces, Grease collector cups. NOTE: plastic back left leg missing, still works. ",
    "asking_cost": "€ 50",
    "percent_discount": "70.4439321392682%",
    "purchase_date": "3/9/2009",
    "original_cost": "€ 169.17",
    "docs": "yes"
  },
  {
    "brand": "Black & Decker",
    "name": "Dustbuster",
    "model": "DV1205N - Dustbuster Extreme",
    "slug": "dustbuster",
    "delta": "€ 40",
    "details": "White/Grey with charger",
    "asking_cost": "€ 30",
    "percent_discount": "57.1428571428571%",
    "purchase_date": "11/15/2008",
    "original_cost": "€ 70",
    "docs": "yes"
  },
  {
    "brand": "Aircoon",
    "name": "Portable Air conditioner",
    "model": "AIRCOON FRESH 120",
    "slug": "ac",
    "delta": "€ 179",
    "details": "With remote, air/water exhaust tube and sash window kit.",
    "asking_cost": "€ 140",
    "percent_discount": "56.1128526645768%",
    "purchase_date": "7/1/2009",
    "original_cost": "€ 319",
    "docs": "yes"
  },
  {
    "brand": "Calor",
    "name": "Standing Fan",
    "model": "",
    "slug": "stand-fan",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Calor",
    "name": "Table Fan",
    "model": "",
    "slug": "fan",
    "delta": "",
    "details": "",
    "asking_cost": "€ 40",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Kenwood",
    "name": "Blender",
    "model": "",
    "slug": "blender",
    "delta": "",
    "details": "Plastic, has a valve on the front for smoothies",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Late 2009",
    "original_cost": "",
    "docs": "yes"
  },
  {
    "brand": "Skil",
    "name": "Drill",
    "model": "",
    "slug": "drill",
    "delta": "",
    "details": "",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Whirlpool",
    "name": "Microwave",
    "model": "",
    "slug": "microwave",
    "delta": "",
    "details": "Front clock / time display has a loose connection (oven still works fine)",
    "asking_cost": "€ 40",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Kitchen Shelving/Cabinets",
    "model": "",
    "slug": "kitchen-shelving",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Ikea",
    "name": "Ikea wall shelves",
    "model": "",
    "slug": "ikea-wall",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Ikea",
    "name": "Wall mounted reading lights",
    "model": "",
    "slug": "reading-lights",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Phillips",
    "name": "Iron",
    "model": "",
    "slug": "iron",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Late 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Hair Dryer",
    "model": "",
    "slug": "hair-dryer",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "October 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Hair Straightener",
    "model": "",
    "slug": "hair-straightener",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "October 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Shower Curtain Rod",
    "model": "",
    "slug": "shower-curtain-rod",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Curtain Rod",
    "model": "",
    "slug": "curtain-rods",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Ikea",
    "name": "Curtains",
    "model": "",
    "slug": "curtains",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Ikea",
    "name": "Ceiling Lights",
    "model": "",
    "slug": "ceiling-lights",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "Ikea",
    "name": "Kitchen Hanging Light",
    "model": "",
    "slug": "red-ceiling-light",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Balcony Planters",
    "model": "",
    "slug": "balcony-planters",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Spring 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Balcony Stools",
    "model": "",
    "slug": "balcony-stools",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Electrical Extension Cords",
    "model": "",
    "slug": "electric-cords",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Humidifier",
    "model": "",
    "slug": "humidifier",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Food Processor",
    "model": "",
    "slug": "food-processor",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": ""
  },
  {
    "brand": "",
    "name": "Alarm Clock",
    "model": "",
    "slug": "alarm-clock",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": ""
  }
];