Crozatier = {}; Crozatier.stuff = [
  {
    "brand": "VIVA",
    "french_details": "52L - White - 6 cooking modes with clock",
    "model": "VVH32C3320",
    "slug": "oven",
    "name": "Oven",
    "category": "Kitchen Appliances",
    "delta": "€ 176.16",
    "details": "52L - White - 6 cooking modes with clock",
    "asking_cost": "€ 175",
    "percent_discount": "50.1651668754984%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 351.16",
    "docs": "",
    "french_name": "Four",
    "rest_localized": ""
  },
  {
    "brand": "VIVA",
    "french_details": "Fridge 225L, Freezer 87L with 3 drawers. Fridge on top",
    "model": "VVC36V00F",
    "slug": "fridge",
    "name": "Fridge/Freezer",
    "category": "Kitchen Appliances",
    "delta": "€ 238.06",
    "details": "Fridge 225L, Freezer 87L with 3 drawers. Fridge on top",
    "asking_cost": "€ 180",
    "percent_discount": "56.9439793331101%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 418.06",
    "docs": "yes",
    "french_name": "Frigo / Congélateur",
    "rest_localized": ""
  },
  {
    "brand": "Siemens",
    "french_details": "Dishwasher (9 couverts, 4 programs)",
    "model": "SF24E233EU",
    "slug": "dishwasher",
    "name": "Dishwasher",
    "category": "Kitchen Appliances",
    "delta": "€ 246.42",
    "details": "Dishwasher (9 couverts, 4 programs)",
    "asking_cost": "€ 180",
    "percent_discount": "57.7880962431406%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 426.42",
    "docs": "yes",
    "french_name": "Lave-vaisselle",
    "rest_localized": ""
  },
  {
    "brand": "Siemens",
    "french_details": "Combo washer-dryer. 5kg capacity. 8 buttons / 15 programs.",
    "model": "WD12D560FF",
    "slug": "washer-dryer",
    "name": "Washer/Dryer",
    "category": "Kitchen Appliances",
    "delta": "€ 352.26",
    "details": "Combo washer-dryer. 5kg capacity. 8 buttons / 15 programs.",
    "asking_cost": "€ 325",
    "percent_discount": "52.0125210406638%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 677.26",
    "docs": "",
    "french_name": "Lave-linge séchant",
    "rest_localized": ""
  },
  {
    "brand": "Glem",
    "french_details": "2 surfaces with front controls",
    "model": "XTDH5C",
    "slug": "glass-cooktop",
    "name": "Glass Cooktop",
    "category": "Kitchen Appliances",
    "delta": "€ 182.61",
    "details": "2 surfaces with front controls",
    "asking_cost": "€ 100",
    "percent_discount": "64.6155479282403%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 282.61",
    "docs": "yes",
    "french_name": "Table de Cuisson (en verre)",
    "rest_localized": ""
  },
  {
    "brand": "Cuisines Mondial Kit",
    "french_details": "Includes a countertop",
    "model": "Australia",
    "slug": "kitchen-shelving",
    "name": "Kitchen Cabinets",
    "category": "Kitchen Appliances",
    "delta": "",
    "details": "Includes a countertop",
    "asking_cost": "€ 400",
    "percent_discount": "",
    "purchase_date": "Nov 2009",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 1140.75",
    "docs": "",
    "french_name": "Armoires de cuisine",
    "rest_localized": ""
  },
  {
    "brand": "VIVA",
    "french_details": "Stainless Steel, 3 speed with 40watt lightbulb",
    "model": "VVA62U150",
    "slug": "stove-hood",
    "name": "Stove Hood",
    "category": "Kitchen Appliances",
    "delta": "€ 43.60",
    "details": "Stainless Steel, 3 speed with 40watt lightbulb",
    "asking_cost": "€ 40",
    "percent_discount": "52.1531100478469%",
    "purchase_date": "22 Dec 2008",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 83.60",
    "docs": "",
    "french_name": "Hotte de cuisine",
    "rest_localized": ""
  },
  {
    "brand": "Whirlpool",
    "french_details": "Front clock / time display has a loose connection (oven still works fine)",
    "model": "VT251",
    "slug": "microwave",
    "name": "Microwave",
    "category": "Kitchen Appliances",
    "delta": "",
    "details": "Front clock / time display has a loose connection (oven still works fine)",
    "asking_cost": "€ 40",
    "percent_discount": "",
    "purchase_date": "Nov 2009",
    "french_category": "Appareils de cuisine",
    "original_cost": "",
    "docs": "",
    "french_name": "Micro-onde",
    "rest_localized": ""
  },
  {
    "brand": "Cuisinart",
    "french_details": "2 sets of surfaces, Grease collector cups. NOTE: plastic back left leg missing, still works. ",
    "model": "CLASS PRO GR4E",
    "slug": "sandwich-press",
    "name": "Sandwich Press",
    "category": "Kitchen Appliances",
    "delta": "€ 129.17",
    "details": "2 sets of surfaces, Grease collector cups. NOTE: plastic back left leg missing, still works. ",
    "asking_cost": "€ 40",
    "percent_discount": "76.3551457114146%",
    "purchase_date": "9 Mar 2009",
    "french_category": "Appareils de cuisine",
    "original_cost": "€ 169.17",
    "docs": "yes",
    "french_name": "Gril sandwich",
    "rest_localized": ""
  },
  {
    "brand": "Kenwood",
    "french_details": "Plastic, has a valve on the front for smoothies",
    "model": "Smoothie Concert SB255",
    "slug": "blender",
    "name": "Blender",
    "category": "Kitchen Appliances",
    "delta": "",
    "details": "Plastic, has a valve on the front for smoothies",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Late 2009",
    "french_category": "Appareils de cuisine",
    "original_cost": "",
    "docs": "yes",
    "french_name": "Mixer",
    "rest_localized": ""
  },
  {
    "brand": "Philips",
    "french_details": "",
    "model": "Comfort HR 7605",
    "slug": "food-processor",
    "name": "Food Processor",
    "category": "Kitchen Appliances",
    "delta": "",
    "details": "",
    "asking_cost": "€ 30",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "french_category": "Appareils de cuisine",
    "original_cost": "approx € 60",
    "docs": "",
    "french_name": "Robot de cuisine",
    "rest_localized": ""
  },
  {
    "brand": "Dyson",
    "french_details": "Bagless",
    "model": "DC19 Origin",
    "slug": "vacuum",
    "name": "Vacuum Cleaner",
    "category": "Home Appliances",
    "delta": "€ 135.59",
    "details": "Bagless",
    "asking_cost": "€ 95",
    "percent_discount": "58.8013357040635%",
    "purchase_date": "29 Jan 2009",
    "french_category": "Appareils électroménagers",
    "original_cost": "€ 230.59",
    "docs": "yes",
    "french_name": "Aspirateur",
    "rest_localized": ""
  },
  {
    "brand": "Aircoon",
    "french_details": "With remote, air/water exhaust tube and sash window kit.",
    "model": "AIRCOON FRESH 120",
    "slug": "ac",
    "name": "Air Conditioner",
    "category": "Home Appliances",
    "delta": "€ 179",
    "details": "With remote, air/water exhaust tube and sash window kit.",
    "asking_cost": "€ 140",
    "percent_discount": "56.1128526645768%",
    "purchase_date": "1 Jul 2009",
    "french_category": "Appareils électroménagers",
    "original_cost": "€ 319",
    "docs": "yes",
    "french_name": "Climatiseur",
    "rest_localized": ""
  },
  {
    "brand": "Calor",
    "french_details": "Has place for mosquito deterrent. We've only used it as a normal fan so we're not sure how well works.",
    "model": "Zenitude Protect VU5060",
    "slug": "stand-fan",
    "name": "Standing Fan",
    "category": "Home Appliances",
    "delta": "",
    "details": "Has place for mosquito deterrent. We've only used it as a normal fan so we're not sure how well works.",
    "asking_cost": "€ 30",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "french_category": "Appareils électroménagers",
    "original_cost": "",
    "docs": "",
    "french_name": "Ventilateur sur pied",
    "rest_localized": ""
  },
  {
    "brand": "Calor",
    "french_details": "Has a place for scent block. We've never used this feature so we're not sure how well it works.",
    "model": "Zenitude VU2050",
    "slug": "fan",
    "name": "Table Fan",
    "category": "Home Appliances",
    "delta": "",
    "details": "Has a place for scent block. We've never used this feature so we're not sure how well it works.",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "french_category": "Appareils électroménagers",
    "original_cost": "",
    "docs": "",
    "french_name": "Ventilateur de table",
    "rest_localized": ""
  },
  {
    "brand": "Addex",
    "french_details": "Travel style, folds in half for easy storage.",
    "model": "CH-1208A",
    "slug": "hair-dryer",
    "name": "Hair Dryer",
    "category": "Electrical Appliances",
    "delta": "",
    "details": "Travel style, folds in half for easy storage.",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Oct 2008",
    "french_category": "Appareils électriques",
    "original_cost": "",
    "docs": "",
    "french_name": "Sèche-cheveux",
    "rest_localized": ""
  },
  {
    "brand": "Remington",
    "french_details": "",
    "model": "Dessange S-2002DS",
    "slug": "hair-straightener",
    "name": "Hair Straightener",
    "category": "Electrical Appliances",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Oct 2008",
    "french_category": "Appareils électriques",
    "original_cost": "",
    "docs": "",
    "french_name": "Lisseurs",
    "rest_localized": ""
  },
  {
    "brand": "Bionaire",
    "french_details": "",
    "model": "CM1",
    "slug": "humidifier",
    "name": "Humidifier",
    "category": "Electrical Appliances",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "french_category": "Appareils électriques",
    "original_cost": "approx. € 60",
    "docs": "",
    "french_name": "Humidificateur",
    "rest_localized": ""
  },
  {
    "brand": "Black&Decker",
    "french_details": "White/Grey with charger",
    "model": "DV1205N - Dustbuster Extreme",
    "slug": "dustbuster",
    "name": "Dustbuster",
    "category": "Home Appliances",
    "delta": "€ 40",
    "details": "White/Grey with charger",
    "asking_cost": "€ 30",
    "percent_discount": "57.1428571428571%",
    "purchase_date": "15 Nov 2008",
    "french_category": "Appareils électroménagers",
    "original_cost": "€ 70",
    "docs": "yes",
    "french_name": "Dustbuster",
    "rest_localized": ""
  },
  {
    "brand": "Skil",
    "french_details": "550 Watt, 13 mm with keyless chuck and variable speed control",
    "model": "Skildrill 6280",
    "slug": "drill",
    "name": "Hammer Drill",
    "category": "Home Appliances",
    "delta": "",
    "details": "550 Watt, 13 mm with keyless chuck and variable speed control",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Nov 2009",
    "french_category": "Appareils électroménagers",
    "original_cost": "",
    "docs": "",
    "french_name": "Perceuse à percussion",
    "rest_localized": ""
  },
  {
    "brand": "Philips",
    "french_details": "2000W",
    "model": "GC 2510",
    "slug": "iron",
    "name": "Iron",
    "category": "Home Appliances",
    "delta": "",
    "details": "2000W",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Late 2008",
    "french_category": "Appareils électroménagers",
    "original_cost": "",
    "docs": "",
    "french_name": "Fer à repasser",
    "rest_localized": ""
  },
  {
    "brand": "Ikea",
    "french_details": "",
    "model": "",
    "slug": "reading-lights",
    "name": "Wall Mounted Lights",
    "category": "Lighting",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "french_category": "Éclairage",
    "original_cost": "",
    "docs": "",
    "french_name": "Lampes murales",
    "rest_localized": ""
  },
  {
    "brand": "Ikea",
    "french_details": "5x Philips fluorescent lightbulbs and 3x Ikea flourescent lightbulbs available also.",
    "model": "LOTORP",
    "slug": "ceiling-lights",
    "name": "Ceiling Lights",
    "category": "Lighting",
    "delta": "",
    "details": "5x Philips fluorescent lightbulbs and 3x Ikea flourescent lightbulbs available also.",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Nov 2008",
    "french_category": "Éclairage",
    "original_cost": "€ 30",
    "docs": "",
    "french_name": "Plafonnier",
    "rest_localized": ""
  },
  {
    "brand": "Ikea",
    "french_details": "Red",
    "model": "365+ HOTTA",
    "slug": "red-ceiling-light",
    "name": "Hanging Light",
    "category": "Lighting",
    "delta": "",
    "details": "Red",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Nov 2008",
    "french_category": "Éclairage",
    "original_cost": "€ 45",
    "docs": "",
    "french_name": "Suspension à lumière",
    "rest_localized": ""
  },
  {
    "brand": "Assorted",
    "french_details": "Various. More details to come.",
    "model": "",
    "slug": "electric-cords",
    "name": "Electrical Cords",
    "category": "Electronics",
    "delta": "",
    "details": "Various. More details to come.",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "",
    "french_category": "Électronique",
    "original_cost": "",
    "docs": "",
    "french_name": "Cordons électriques",
    "rest_localized": ""
  },
  {
    "brand": "Philips",
    "french_details": "Antenna wire broken but still seems to work fine.",
    "model": "AJ3540/12",
    "slug": "alarm-clock",
    "name": "Alarm Clock",
    "category": "Electronics",
    "delta": "",
    "details": "Antenna wire broken but still seems to work fine.",
    "asking_cost": "€ 5",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "french_category": "Électronique",
    "original_cost": "approx € 15",
    "docs": "",
    "french_name": "Radio-réveil",
    "rest_localized": ""
  },
  {
    "brand": "Ikea",
    "french_details": "Black. 3pc 55cm (1 unopened), 1pc 185cm",
    "model": "RIBBA",
    "slug": "ikea-wall",
    "name": "Wall Shelves",
    "category": "Home Goods",
    "delta": "",
    "details": "Black. 3pc 55cm (1 unopened), 1pc 185cm",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Nov 2009",
    "french_category": "Accueil marchandises",
    "original_cost": "",
    "docs": "",
    "french_name": "Étagères murales",
    "rest_localized": ""
  },
  {
    "brand": "?",
    "french_details": "Purchased at BHV. Resizable, spring-loaded.",
    "model": "",
    "slug": "shower-curtain-rod",
    "name": "Shower Curtain Rod",
    "category": "Home Goods",
    "delta": "",
    "details": "Purchased at BHV. Resizable, spring-loaded.",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Nov 2008",
    "french_category": "Accueil marchandises",
    "original_cost": "",
    "docs": "",
    "french_name": "Tige de rideau de douche",
    "rest_localized": ""
  },
  {
    "brand": "Ikea",
    "french_details": "Blue curtains are available if you'd like, for free (although they have cat hair on them).",
    "model": "",
    "slug": "curtain-rods",
    "name": "Curtain Rod",
    "category": "Home Goods",
    "delta": "",
    "details": "Blue curtains are available if you'd like, for free (although they have cat hair on them).",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Nov 2008",
    "french_category": "Accueil marchandises",
    "original_cost": "",
    "docs": "",
    "french_name": "Tringle à rideau",
    "rest_localized": ""
  },
  {
    "brand": "Marchioro",
    "french_details": "Colored Manila, with black balcony support.",
    "model": "NARA L60xL20xH16 lt.12 (L24\"xW8\"xH6.5\")",
    "slug": "balcony-planters",
    "name": "Balcony Planters",
    "category": "Home Goods",
    "delta": "",
    "details": "Colored Manila, with black balcony support.",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Spring 2009",
    "french_category": "Accueil marchandises",
    "original_cost": "approx € 25",
    "docs": "",
    "french_name": "Jardinières",
    "rest_localized": ""
  },
  {
    "brand": "Monoprix",
    "french_details": "Folding",
    "model": "",
    "slug": "balcony-stools",
    "name": "Balcony Stools",
    "category": "Home Goods",
    "delta": "",
    "details": "Folding",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "french_category": "Accueil marchandises",
    "original_cost": "approx € 25",
    "docs": "",
    "french_name": "Tabourets pliants",
    "rest_localized": ""
  }
];