Crozatier = {}; Crozatier.stuff = [
  {
    "brand": "VIVA",
    "slug": "stove-hood",
    "model": "VVA62U150",
    "name": "Stove Hood",
    "delta": "€ 43.60",
    "details": "Stainless Steel, 3 speed with 40watt lightbulb",
    "asking_cost": "€ 40",
    "percent_discount": "52.1531100478469%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 83.60",
    "docs": "",
    "french_name": ""
  },
  {
    "brand": "VIVA",
    "slug": "oven",
    "model": "VVH32C3320",
    "name": "Oven",
    "delta": "€ 176.16",
    "details": "52L - White - 6 cooking modes with clock",
    "asking_cost": "€ 175",
    "percent_discount": "50.1651668754984%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 351.16",
    "docs": "",
    "french_name": "Four"
  },
  {
    "brand": "Glem",
    "slug": "glass-cooktop",
    "model": "XTDH5C",
    "name": "Glass Cooktop",
    "delta": "€ 182.61",
    "details": "2 surfaces with front controls",
    "asking_cost": "€ 100",
    "percent_discount": "64.6155479282403%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 282.61",
    "docs": "yes",
    "french_name": "Table de Cuisson (en verre)"
  },
  {
    "brand": "VIVA",
    "slug": "fridge",
    "model": "VVC36V00F",
    "name": "Fridge/Freezer",
    "delta": "€ 238.06",
    "details": "Fridge 225L, Freezer 87L with 3 drawers. Fridge on top",
    "asking_cost": "€ 180",
    "percent_discount": "56.9439793331101%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 418.06",
    "docs": "yes",
    "french_name": "Frigo / Congélateur"
  },
  {
    "brand": "Siemens",
    "slug": "dishwasher",
    "model": "SF24E233EU",
    "name": "Dishwasher",
    "delta": "€ 246.42",
    "details": "Dishwasher (9 couverts, 4 programs)",
    "asking_cost": "€ 180",
    "percent_discount": "57.7880962431406%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 426.42",
    "docs": "yes",
    "french_name": "Lave-vaisselle"
  },
  {
    "brand": "Siemens",
    "slug": "washer-dryer",
    "model": "WD12D560FF",
    "name": "Washer/Dryer",
    "delta": "€ 377.26",
    "details": "Combo washer-dryer. 5kg capacity. 8 buttons / 15 programs.",
    "asking_cost": "€ 300",
    "percent_discount": "55.7038655759974%",
    "purchase_date": "12/22/2008",
    "original_cost": "€ 677.26",
    "docs": "",
    "french_name": "Lave-linge séchant"
  },
  {
    "brand": "Dyson",
    "slug": "vacuum",
    "model": "DC19 Origin",
    "name": "Vacuum Cleaner",
    "delta": "€ 135.59",
    "details": "Bagless",
    "asking_cost": "€ 95",
    "percent_discount": "58.8013357040635%",
    "purchase_date": "1/29/2009",
    "original_cost": "€ 230.59",
    "docs": "yes",
    "french_name": "Aspirateur"
  },
  {
    "brand": "Cuisinart",
    "slug": "sandwich-press",
    "model": "CLASS PRO GR4E",
    "name": "Sandwich Press",
    "delta": "€ 129.17",
    "details": "2 sets of surfaces, Grease collector cups. NOTE: plastic back left leg missing, still works. ",
    "asking_cost": "€ 40",
    "percent_discount": "76.3551457114146%",
    "purchase_date": "3/9/2009",
    "original_cost": "€ 169.17",
    "docs": "yes",
    "french_name": "Gril sandwich"
  },
  {
    "brand": "Black&Decker",
    "slug": "dustbuster",
    "model": "DV1205N - Dustbuster Extreme",
    "name": "Dustbuster",
    "delta": "€ 40",
    "details": "White/Grey with charger",
    "asking_cost": "€ 30",
    "percent_discount": "57.1428571428571%",
    "purchase_date": "11/15/2008",
    "original_cost": "€ 70",
    "docs": "yes",
    "french_name": "Dustbuster"
  },
  {
    "brand": "Aircoon",
    "slug": "ac",
    "model": "AIRCOON FRESH 120",
    "name": "Air Conditioner",
    "delta": "€ 179",
    "details": "With remote, air/water exhaust tube and sash window kit.",
    "asking_cost": "€ 140",
    "percent_discount": "56.1128526645768%",
    "purchase_date": "7/1/2009",
    "original_cost": "€ 319",
    "docs": "yes",
    "french_name": "Climatiseur"
  },
  {
    "brand": "Calor",
    "slug": "stand-fan",
    "model": "",
    "name": "Standing Fan",
    "delta": "",
    "details": "",
    "asking_cost": "€ 30",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Ventilateur sur pied"
  },
  {
    "brand": "Calor",
    "slug": "fan",
    "model": "",
    "name": "Table Fan",
    "delta": "",
    "details": "",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Ventilateur de table"
  },
  {
    "brand": "Kenwood",
    "slug": "blender",
    "model": "",
    "name": "Blender",
    "delta": "",
    "details": "Plastic, has a valve on the front for smoothies",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Late 2009",
    "original_cost": "",
    "docs": "yes",
    "french_name": "Mixer"
  },
  {
    "brand": "Skil",
    "slug": "drill",
    "model": "",
    "name": "Drill",
    "delta": "",
    "details": "",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Perceuse"
  },
  {
    "brand": "Whirlpool",
    "slug": "microwave",
    "model": "",
    "name": "Microwave",
    "delta": "",
    "details": "Front clock / time display has a loose connection (oven still works fine)",
    "asking_cost": "€ 40",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Micro-onde"
  },
  {
    "brand": "",
    "slug": "kitchen-shelving",
    "model": "",
    "name": "Kitchen Cabinets",
    "delta": "",
    "details": "",
    "asking_cost": "€ 200",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Armoires de cuisine"
  },
  {
    "brand": "Ikea",
    "slug": "ikea-wall",
    "model": "",
    "name": "Wall Shelves",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Étagères murales"
  },
  {
    "brand": "Ikea",
    "slug": "reading-lights",
    "model": "",
    "name": "Wall Mounted Lights",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Lampes murales"
  },
  {
    "brand": "Phillips",
    "slug": "iron",
    "model": "",
    "name": "Iron",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Late 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Fer à repasser"
  },
  {
    "brand": "",
    "slug": "hair-dryer",
    "model": "",
    "name": "Hair Dryer",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "October 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Sèche-cheveux"
  },
  {
    "brand": "",
    "slug": "hair-straightener",
    "model": "",
    "name": "Hair Straightener",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "October 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Lisseurs"
  },
  {
    "brand": "",
    "slug": "shower-curtain-rod",
    "model": "",
    "name": "Shower Curtain Rod",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Tige de rideau de douche"
  },
  {
    "brand": "",
    "slug": "curtain-rods",
    "model": "",
    "name": "Curtain Rod",
    "delta": "",
    "details": "Blue curtains are available if you'd like, for free (although they have cat hair on them).",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "",
    "docs": "",
    "french_name": "Tringle à rideau"
  },
  {
    "brand": "Ikea",
    "slug": "ceiling-lights",
    "model": "LOTORP",
    "name": "Ceiling Lights",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "€ 30",
    "docs": "",
    "french_name": "Plafonnier"
  },
  {
    "brand": "Ikea",
    "slug": "red-ceiling-light",
    "model": "365+ HOTTA",
    "name": "Hanging Light",
    "delta": "",
    "details": "Red",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "November 2008",
    "original_cost": "€ 45",
    "docs": "",
    "french_name": "Suspension à lumière"
  },
  {
    "brand": "",
    "slug": "balcony-planters",
    "model": "",
    "name": "Balcony Planters",
    "delta": "",
    "details": "",
    "asking_cost": "€ 10",
    "percent_discount": "",
    "purchase_date": "Spring 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Jardinières"
  },
  {
    "brand": "",
    "slug": "balcony-stools",
    "model": "",
    "name": "Balcony Stools",
    "delta": "",
    "details": "",
    "asking_cost": "€ 15",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Tabourets pliants"
  },
  {
    "brand": "",
    "slug": "electric-cords",
    "model": "",
    "name": "Electrical Cords",
    "delta": "",
    "details": "",
    "asking_cost": "",
    "percent_discount": "",
    "purchase_date": "",
    "original_cost": "",
    "docs": "",
    "french_name": "Cordons électriques"
  },
  {
    "brand": "",
    "slug": "humidifier",
    "model": "",
    "name": "Humidifier",
    "delta": "",
    "details": "",
    "asking_cost": "€ 20",
    "percent_discount": "",
    "purchase_date": "Early 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Humidificateur"
  },
  {
    "brand": "",
    "slug": "food-processor",
    "model": "",
    "name": "Food Processor",
    "delta": "",
    "details": "",
    "asking_cost": "€ 30",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Robot de cuisine"
  },
  {
    "brand": "",
    "slug": "alarm-clock",
    "model": "",
    "name": "Alarm Clock",
    "delta": "",
    "details": "",
    "asking_cost": "€ 8",
    "percent_discount": "",
    "purchase_date": "Summer 2009",
    "original_cost": "",
    "docs": "",
    "french_name": "Radio-réveil"
  }
];